Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

Find the shape, rank and size of the tensors you created in 1.

In [1]:
import tensorflow as tf
import numpy as np

scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [2]:
vector = tf.constant([10, 20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [4]:
matrix = tf.constant([[10, 10],
                     [10, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10]], dtype=int32)>

In [7]:
tensor = tf.constant([
    [[1, 2], [1, 2]],
    [[4, 5], [5, 6]]])
tensor


<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [1, 2]],

       [[4, 5],
        [5, 6]]], dtype=int32)>

Create two tensors containing random values between 0 and 1 with shape [5, 300].
Multiply the two tensors you created in 3 using matrix multiplication.
Multiply the two tensors you created in 3 using dot product.

In [8]:
tensor1 = tf.random.uniform(shape=[5, 300])
tensor2 = tf.random.uniform(shape=[5, 300])
tf.matmul(tf.transpose(tensor1), tensor2)
tf.tensordot(tf.transpose(tensor1), tensor2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[2.050677  , 1.7533675 , 1.546669  , ..., 1.4183288 , 1.9549133 ,
        1.647928  ],
       [2.0709748 , 1.2786198 , 1.4593939 , ..., 1.3536068 , 1.6180488 ,
        0.9211316 ],
       [0.8137279 , 0.7279152 , 0.68913037, ..., 0.46476108, 0.67098933,
        0.6758403 ],
       ...,
       [1.5654805 , 1.2949961 , 1.040189  , ..., 1.2818546 , 1.5455797 ,
        1.6143122 ],
       [1.1175454 , 1.1495335 , 1.0574149 , ..., 0.45807755, 1.1471132 ,
        0.3851225 ],
       [1.1458708 , 0.98352045, 0.8671541 , ..., 0.62139213, 1.0765972 ,
        0.6618996 ]], dtype=float32)>

Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [9]:
tensor3 = tf.random.uniform(shape=[224, 224, 3])

Find the min and max values of the tensor you created in 6 along the first axis.

In [12]:
min = tf.reduce_min(tensor3).numpy()
min

1.2755394e-05

In [13]:
max = tf.reduce_max(tensor3).numpy()
max

0.99999726

Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [14]:
tensor4 = tf.random.uniform(shape=[1, 224, 224, 3])
squeezed4 = tf.squeeze(tensor4)

Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [21]:
tens = random_tensor = tf.random.uniform(shape=[10], minval=0, maxval=100, dtype=tf.int32)
max = tf.argmax(tens).numpy()
max

9

One-hot encode the tensor you created in 9.

In [22]:
num = len(tf.unique(tens)[0])
tensonehot = tf.one_hot(indices=tens, depth=num)
tensonehot

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>